//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockZilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresse
    {
        public int Id { get; set; }
        public string adresses { get; set; }
        public string pays { get; set; }
        public string ville { get; set; }
        public Nullable<int> code_postal { get; set; }
        public string id_user { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
